# Generated by Django 3.1.2 on 2021-12-10 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=150)),
                ('birthday', models.DateField()),
                ('fechaAlta', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=150)),
                ('biography', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proyect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('endingReport', models.CharField(max_length=255)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='nucleo.category', verbose_name='category')),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='nucleo.employee', verbose_name='employee')),
            ],
        ),
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscriptionDate', models.DateField(auto_now_add=True)),
                ('role', models.CharField(max_length=100)),
                ('clientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='nucleo.client', verbose_name='client')),
                ('proyectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyect', to='nucleo.proyect', verbose_name='proyect')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employee', to='nucleo.user', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='client',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Client', to='nucleo.user', verbose_name='User'),
        ),
    ]
