# Generated by Django 3.1.2 on 2022-01-04 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nucleo', '0004_auto_20220104_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employee', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='User'),
        ),
    ]
