# Generated by Django 3.1.2 on 2022-02-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0008_auto_20220113_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participate',
            name='role',
            field=models.CharField(choices=[('Organizador', 'Organizador del proyecto'), ('Participante', 'Participante del evento')], default='Participante', max_length=100),
        ),
        migrations.AlterField(
            model_name='proyect',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='proyect',
            name='endingReport',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
