# Generated by Django 3.1.2 on 2022-01-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
    ]
